language: node_js 

services:
  - docker

before_install:
  - docker build -t solidearthvr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true solidearthvr/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-430752736366"
  bucket_path: "docker-react"
  edge: true
  on:
    branch: master
