language: node_js 

services:
  - docker

before_install:
  - docker build -t solidearthvr/docker-react -f frontend/Dockerfile.dev frontend

script:
  - docker run -e CI=true solidearthvr/docker-react npm run test

#test